export const users = {
  itemsPerPage: 100,
  page: 1,
  pageCount: 1,
  itemCount: 3,
  results: [
    {
      id: 1,
      username: "admin",
      first_name: "",
      following: null,
      roll: [
        "menu_users",
        "menu_statistics",
        "menu_settings",
        "device_delete",
        "device_edit",
        "device_settings",
        "device_data",
        "device_download",
        "settings_valve_open",
        "settings_valve_close",
        "settings_valve_other",
        "binding_by_region",
        "binding_by_district",
        "branch_individuals",
        "branch_entity",
        "no_reg_device_edit",
      ],
      last_name: "",
      email: "admin@sarf.uz",
      phone_number: "",
      region_id: null,
      district_id: null,
      users_tree: [
        {
          id: 34,
          username: "aholi",
          first_name: "",
          following: 1,
          roll: ["menu_statistics"],
          last_name: "",
          email: "maxts1990@gmail.com",
          phone_number: "",
          region_id: "г. Ташкент",
          district_id: "Районы города Ташкента",
          users_tree: [
            {
              id: 70,
              username: "01HUDUDGAZ_AHOLI",
              first_name: "",
              following: 34,
              roll: [
                "menu_statistics",
                "device_download",
                "branch_individuals",
              ],
              last_name: "",
              email: "",
              phone_number: "",
              region_id: null,
              district_id: null,
              users_tree: [],
            },
            {
              id: 67,
              username: "AHOLI_BUXORO",
              first_name: "",
              following: 34,
              roll: [
                "menu_statistics",
                "device_download",
                "binding_by_region",
                "binding_by_district",
                "branch_individuals",
              ],
              last_name: "",
              email: null,
              phone_number: "",
              region_id: "Бухарская область",
              district_id: null,
              users_tree: [],
            },
            {
              id: 64,
              username: "AHOLI_NAMANGAN",
              first_name: "",
              following: 34,
              roll: [
                "menu_statistics",
                "device_download",
                "binding_by_region",
                "binding_by_district",
                "branch_individuals",
              ],
              last_name: "",
              email: null,
              phone_number: "",
              region_id: "Наманганская область",
              district_id: null,
              users_tree: [],
            },
            {
              id: 65,
              username: "AHOLI_QORAQALPOG'ISTON",
              first_name: "",
              following: 34,
              roll: [
                "menu_statistics",
                "device_download",
                "binding_by_region",
                "binding_by_district",
                "branch_individuals",
              ],
              last_name: "",
              email: null,
              phone_number: "",
              region_id: "Республика Каракалпакстан",
              district_id: null,
              users_tree: [],
            },
            {
              id: 35,
              username: "AHOLI_TOSHKENT",
              first_name: "",
              following: 34,
              roll: [
                "binding_by_region",
                "menu_users",
                "menu_statistics",
                "device_download",
                "settings_valve_open",
                "settings_valve_close",
                "branch_individuals",
              ],
              last_name: "",
              email: "",
              phone_number: "",
              region_id: "г. Ташкент",
              district_id: "Районы города Ташкента",
              users_tree: [],
            },
            {
              id: 69,
              username: "AHOLI_TOSHVILOYATI",
              first_name: "",
              following: 34,
              roll: [
                "menu_statistics",
                "settings_valve_open",
                "settings_valve_close",
                "binding_by_region",
                "binding_by_district",
                "branch_individuals",
                "no_reg_device_edit",
              ],
              last_name: "",
              email: "sarf-meter@mail.ru",
              phone_number: "",
              region_id: "Ташкентская область",
              district_id: null,
              users_tree: [],
            },
            {
              id: 36,
              username: "Unicon",
              first_name: "",
              following: 34,
              roll: [
                "device_settings",
                "device_download",
                "device_data",
                "settings_valve_open",
                "menu_statistics",
                "device_edit",
                "settings_valve_close",
              ],
              last_name: "",
              email: null,
              phone_number: "",
              region_id: "г. Ташкент",
              district_id: "Районы города Ташкента",
              users_tree: [],
            },
          ],
        },
        {
          id: 33,
          username: "korxona",
          first_name: "",
          following: 1,
          roll: [],
          last_name: "",
          email: "",
          phone_number: "",
          region_id: null,
          district_id: null,
          users_tree: [
            {
              id: 63,
              username: "HUDUDGAZ",
              first_name: "",
              following: 33,
              roll: [
                "menu_statistics",
                "binding_by_region",
                "binding_by_district",
                "branch_entity",
              ],
              last_name: "",
              email: "",
              phone_number: "",
              region_id: "г. Ташкент",
              district_id: "Районы города Ташкента",
              users_tree: [],
            },
            {
              id: 43,
              username: "HUDUDGAZ_ANDIJON",
              first_name: "",
              following: 33,
              roll: [
                "menu_statistics",
                "device_download",
                "binding_by_region",
                "binding_by_district",
                "branch_entity",
                "no_reg_device_edit",
              ],
              last_name: "",
              email: null,
              phone_number: "",
              region_id: "Андижанская область",
              district_id: null,
              users_tree: [],
            },
            {
              id: 39,
              username: "HUDUDGAZ_BUXORO",
              first_name: "",
              following: 33,
              roll: [
                "menu_statistics",
                "device_download",
                "binding_by_region",
                "binding_by_district",
                "branch_entity",
              ],
              last_name: "",
              email: null,
              phone_number: "",
              region_id: "Бухарская область",
              district_id: null,
              users_tree: [],
            },
            {
              id: 47,
              username: "HUDUDGAZ_FARG'ONA",
              first_name: "",
              following: 33,
              roll: [
                "menu_statistics",
                "device_download",
                "binding_by_region",
                "binding_by_district",
                "branch_entity",
                "no_reg_device_edit",
              ],
              last_name: "",
              email: null,
              phone_number: "",
              region_id: "Ферганская область",
              district_id: null,
              users_tree: [],
            },
            {
              id: 41,
              username: "HUDUDGAZ_JIZZAX",
              first_name: "",
              following: 33,
              roll: [
                "menu_statistics",
                "device_download",
                "binding_by_region",
                "binding_by_district",
                "branch_entity",
              ],
              last_name: "",
              email: null,
              phone_number: "",
              region_id: "Джизакская область",
              district_id: null,
              users_tree: [],
            },
            {
              id: 37,
              username: "HUDUDGAZ_NAMANGAN",
              first_name: "",
              following: 33,
              roll: [
                "branch_entity",
                "binding_by_region",
                "menu_statistics",
                "branch_individuals",
                "no_reg_device_edit",
              ],
              last_name: "",
              email: null,
              phone_number: "",
              region_id: "Наманганская область",
              district_id: null,
              users_tree: [],
            },
            {
              id: 44,
              username: "HUDUDGAZ_NAVOI",
              first_name: "",
              following: 33,
              roll: [
                "menu_statistics",
                "device_download",
                "binding_by_region",
                "binding_by_district",
                "branch_entity",
              ],
              last_name: "",
              email: null,
              phone_number: "",
              region_id: "Навоийская область",
              district_id: null,
              users_tree: [],
            },
            {
              id: 42,
              username: "HUDUDGAZ_QASHQADARYO",
              first_name: "",
              following: 33,
              roll: [
                "menu_statistics",
                "device_download",
                "binding_by_region",
                "binding_by_district",
                "branch_entity",
              ],
              last_name: "",
              email: null,
              phone_number: "",
              region_id: "Кашкадарьинская область",
              district_id: null,
              users_tree: [],
            },
            {
              id: 50,
              username: "HUDUDGAZ_QORAQALPOG'ISTON",
              first_name: "",
              following: 33,
              roll: [
                "menu_statistics",
                "device_download",
                "binding_by_region",
                "binding_by_district",
                "branch_entity",
                "branch_individuals",
              ],
              last_name: "",
              email: "1",
              phone_number: "",
              region_id: "Республика Каракалпакстан",
              district_id: null,
              users_tree: [],
            },
            {
              id: 40,
              username: "HUDUDGAZ_SAMARQAND",
              first_name: "",
              following: 33,
              roll: [
                "menu_statistics",
                "device_download",
                "binding_by_region",
                "binding_by_district",
                "branch_entity",
              ],
              last_name: "",
              email: null,
              phone_number: "",
              region_id: "Самаркандская область",
              district_id: null,
              users_tree: [],
            },
            {
              id: 72,
              username: "HUDUDGAZ_SAMARQAND2",
              first_name: "",
              following: 33,
              roll: [
                "menu_statistics",
                "device_download",
                "settings_valve_open",
                "settings_valve_close",
                "binding_by_region",
                "binding_by_district",
                "branch_entity",
              ],
              last_name: "",
              email: null,
              phone_number: "",
              region_id: "Самаркандская область",
              district_id: null,
              users_tree: [],
            },
            {
              id: 46,
              username: "HUDUDGAZ_SIRDARYO",
              first_name: "",
              following: 33,
              roll: [
                "menu_statistics",
                "device_download",
                "binding_by_region",
                "binding_by_district",
                "branch_entity",
              ],
              last_name: "",
              email: null,
              phone_number: "",
              region_id: "Сырдарьинская область",
              district_id: null,
              users_tree: [],
            },
            {
              id: 45,
              username: "HUDUDGAZ_SURXONDARYO",
              first_name: "",
              following: 33,
              roll: [
                "menu_statistics",
                "device_download",
                "binding_by_region",
                "binding_by_district",
                "branch_entity",
              ],
              last_name: "",
              email: null,
              phone_number: "",
              region_id: "Сурхандарьинская область",
              district_id: null,
              users_tree: [],
            },
            {
              id: 38,
              username: "HUDUDGAZ_TOSHKENT",
              first_name: "",
              following: 33,
              roll: [
                "menu_statistics",
                "device_download",
                "binding_by_region",
                "binding_by_district",
                "branch_entity",
                "settings_valve_open",
                "settings_valve_close",
              ],
              last_name: "",
              email: null,
              phone_number: "",
              region_id: "г. Ташкент",
              district_id: null,
              users_tree: [
                {
                  id: 60,
                  username: "HUDUDGAZ_BEKTEMIR",
                  first_name: "",
                  following: 38,
                  roll: [
                    "menu_statistics",
                    "device_download",
                    "binding_by_district",
                    "branch_entity",
                  ],
                  last_name: "",
                  email: null,
                  phone_number: "",
                  region_id: "г. Ташкент",
                  district_id: "Бектемирский район",
                  users_tree: [],
                },
                {
                  id: 52,
                  username: "HUDUDGAZ_CHILONZOR",
                  first_name: "",
                  following: 38,
                  roll: [
                    "menu_statistics",
                    "device_download",
                    "branch_entity",
                    "binding_by_district",
                  ],
                  last_name: "",
                  email: null,
                  phone_number: "",
                  region_id: "г. Ташкент",
                  district_id: "Чиланзарский район",
                  users_tree: [],
                },
                {
                  id: 53,
                  username: "HUDUDGAZ_MIROBOD",
                  first_name: "",
                  following: 38,
                  roll: [
                    "menu_statistics",
                    "device_download",
                    "binding_by_district",
                    "branch_entity",
                  ],
                  last_name: "",
                  email: null,
                  phone_number: "",
                  region_id: "г. Ташкент",
                  district_id: "Мирабадский район",
                  users_tree: [],
                },
                {
                  id: 61,
                  username: "HUDUDGAZ_MIRZOULUGBEK",
                  first_name: "",
                  following: 38,
                  roll: [
                    "menu_statistics",
                    "device_download",
                    "binding_by_district",
                    "branch_entity",
                  ],
                  last_name: "",
                  email: null,
                  phone_number: "",
                  region_id: "г. Ташкент",
                  district_id: "Мирзо-Улугбекский район",
                  users_tree: [],
                },
                {
                  id: 57,
                  username: "HUDUDGAZ_OLMAZOR",
                  first_name: "",
                  following: 38,
                  roll: [
                    "menu_statistics",
                    "device_download",
                    "binding_by_district",
                    "branch_entity",
                  ],
                  last_name: "",
                  email: null,
                  phone_number: "",
                  region_id: "г. Ташкент",
                  district_id: "Алмазарский район",
                  users_tree: [],
                },
                {
                  id: 58,
                  username: "HUDUDGAZ_SERGELI",
                  first_name: "",
                  following: 38,
                  roll: [
                    "menu_statistics",
                    "device_download",
                    "binding_by_district",
                    "branch_entity",
                  ],
                  last_name: "",
                  email: null,
                  phone_number: "",
                  region_id: "г. Ташкент",
                  district_id: "Сергелийский район",
                  users_tree: [],
                },
                {
                  id: 54,
                  username: "HUDUDGAZ_SHAYXONTOHUR",
                  first_name: "",
                  following: 38,
                  roll: [
                    "menu_statistics",
                    "device_download",
                    "binding_by_district",
                    "branch_entity",
                  ],
                  last_name: "",
                  email: null,
                  phone_number: "",
                  region_id: "г. Ташкент",
                  district_id: "Шайхантахурский район",
                  users_tree: [],
                },
                {
                  id: 59,
                  username: "HUDUDGAZ_UCHTEPA",
                  first_name: "",
                  following: 38,
                  roll: [
                    "menu_statistics",
                    "device_download",
                    "binding_by_district",
                    "branch_entity",
                  ],
                  last_name: "",
                  email: null,
                  phone_number: "",
                  region_id: "г. Ташкент",
                  district_id: "Учтепинский район",
                  users_tree: [],
                },
                {
                  id: 51,
                  username: "HUDUDGAZ_YAKKASAROY",
                  first_name: "",
                  following: 38,
                  roll: [
                    "menu_statistics",
                    "device_download",
                    "binding_by_district",
                    "branch_entity",
                  ],
                  last_name: "",
                  email: null,
                  phone_number: "",
                  region_id: "г. Ташкент",
                  district_id: "Яккасарайский район",
                  users_tree: [],
                },
                {
                  id: 62,
                  username: "HUDUDGAZ_YANGIHAYOT",
                  first_name: "",
                  following: 38,
                  roll: [
                    "menu_statistics",
                    "device_download",
                    "binding_by_district",
                    "branch_entity",
                  ],
                  last_name: "",
                  email: null,
                  phone_number: "",
                  region_id: "г. Ташкент",
                  district_id: "Янги хаёт",
                  users_tree: [],
                },
                {
                  id: 55,
                  username: "HUDUDGAZ_YASHNOBOD",
                  first_name: "",
                  following: 38,
                  roll: [
                    "menu_statistics",
                    "device_download",
                    "binding_by_district",
                    "branch_entity",
                  ],
                  last_name: "",
                  email: null,
                  phone_number: "",
                  region_id: "г. Ташкент",
                  district_id: "Яшнободский район",
                  users_tree: [],
                },
                {
                  id: 56,
                  username: "HUDUDGAZ_YUNUSOBOD",
                  first_name: "",
                  following: 38,
                  roll: [
                    "menu_statistics",
                    "device_download",
                    "binding_by_district",
                    "branch_entity",
                  ],
                  last_name: "",
                  email: null,
                  phone_number: "",
                  region_id: "г. Ташкент",
                  district_id: "Юнусабадский район",
                  users_tree: [],
                },
              ],
            },
            {
              id: 49,
              username: "HUDUDGAZ_TOSHKENTVILOYATI",
              first_name: "",
              following: 33,
              roll: [
                "menu_statistics",
                "device_download",
                "binding_by_region",
                "binding_by_district",
                "branch_entity",
              ],
              last_name: "",
              email: null,
              phone_number: "",
              region_id: "Ташкентская область",
              district_id: null,
              users_tree: [],
            },
            {
              id: 48,
              username: "HUDUDGAZ_XORAZM",
              first_name: "",
              following: 33,
              roll: [
                "menu_statistics",
                "device_download",
                "binding_by_region",
                "binding_by_district",
                "branch_entity",
              ],
              last_name: "",
              email: null,
              phone_number: "",
              region_id: "Хорезмская область",
              district_id: null,
              users_tree: [],
            },
          ],
        },
      ],
    },
    {
      id: 66,
      username: "inspektor",
      first_name: "",
      following: null,
      roll: [
        "menu_users",
        "menu_statistics",
        "menu_settings",
        "device_delete",
        "device_edit",
        "device_settings",
        "device_data",
        "device_download",
        "settings_valve_open",
        "settings_valve_close",
        "settings_valve_other",
        "binding_by_region",
        "binding_by_district",
        "branch_individuals",
        "branch_entity",
        "no_reg_device_edit",
      ],
      last_name: "",
      email: "adnin@gurumail.xyz",
      phone_number: "",
      region_id: null,
      district_id: null,
      users_tree: [],
    },
    {
      id: 71,
      username: "TOSHGAZ",
      first_name: "",
      following: null,
      roll: ["settings_valve_open", "settings_valve_close"],
      last_name: "",
      email: "",
      phone_number: "",
      region_id: "г. Ташкент",
      district_id: null,
      users_tree: [],
    },
  ],
};
